name: Deploy to AWS ECS
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Push Docker Image
      run: |
        docker build -t my-app .
        docker tag my-app:latest ${AWS_ECR_REPO}:latest
        echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login -u AWS --password-stdin ${AWS_ECR_REPO}
        docker push ${AWS_ECR_REPO}:latest
    - name: Update ECS Service
      run: |
        aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment